import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const interFont = Inter({ subsets: ["latin"] });

const KaioFont = localFont({
  variable: "--font-kaio",
  src: "./fonts/kaio-bold.woff2",
});

export const metadata = {
  title: "Codacty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${KaioFont.variable} ${interFont.className} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
